manual_mappings = {
    'bristol bay': 'Bristol Bay Borough',
    'haines': 'Haines Borough',
    'skagway': 'Skagway Municipality',
    'yakutat': 'Yakutat City and Borough',
    'alpine': 'Alpine County',
    'mariposa': 'Mariposa County',
    'echols': 'Echols County',
    'kalawao': 'Kalawao County',
    'mccreary': 'McCreary County',
    'plaquemines': 'Plaquemines Parish',
    'st. bernard': 'St. Bernard Parish',
    'st. john the baptist': 'St. John the Baptist Parish',
    'oscoda': 'Oscoda County',
    'banner': 'Banner County',
    'esmeralda': 'Esmeralda County',
    'eureka': 'Eureka County',
    'lander': 'Lander County',
    'nye': 'Nye County',
    'storey': 'Storey County',
    'los alamos': 'Los Alamos County',
    'currituck': 'Currituck County',
    'borden': 'Borden County',
    'glasscock': 'Glasscock County',
    'jim hogg': 'Jim Hogg County',
    'kenedy': 'Kenedy County',
    'loving': 'Loving County',
    'mcmullen': 'McMullen County',
    'zapata': 'Zapata County',
    'amelia': 'Amelia County',
    'arlington': 'Arlington County',
    'bland': 'Bland County',
    'goochland': 'Goochland County',
    'henrico': 'Henrico County',
    'james': 'James City County',
    'king and queen': 'King and Queen County',
    'king george': 'King George County',
    'mathews': 'Mathews County',
    'new kent': 'New Kent County',
    'powhatan': 'Powhatan County',
    'prince george': 'Prince George County',
    'spotsylvania': 'Spotsylvania County',
    # Add more mappings as necessary...
}
